# Generated by Django 4.2.11 on 2024-03-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
